version: '3.3'
services:
  atmosphere-service-products:
    build: .
    image: atmosphere-service-products
    container_name: atmosphere-service-products
    restart: always
    ports:
      - "18080:18080"
    volumes:
      - "${HOME}/.m2:/root/.m2"
